name: "Hub Mirror Action"
description: "Mirror the organization repos between hub (github/gitee)."
author: "yikun"
branding:
  icon: "upload-cloud"
  color: "gray-dark"
inputs:
  dst_key:
    description: "The private SSH key which is used to push code in destination hub."
    required: true
  dst_token:
    description: "The app token which is used to create repo in destination hub."
    required: true
  dst:
    description: "Destination name. Such as `gitee/nonelittlesong`."
    required: true
  src:
    description: "Source name. Such as `github/nonelittlesong`."
    required: true
  account_type:
    description: "The account type. Such as org, user."
    default: 'user'
    required: false
  clone_style:
    description: "The git clone style, https or ssh."
    default: 'https'
    required: false
  cache_path:
    description: "The path to cache the source repos code."
    default: '/github/workspace/github-cache'
    required: false
  black_list:
    description: "High priority, the black list of mirror repo. like 'repo1,repo2,repo3'"
    default: ''
    required: false
  white_list:
    description: "Low priority, the white list of mirror repo. like 'repo1,repo2,repo3'"
    default: ''
    required: false
  static_list:
    description: "Only mirror repo in the static list, but don't get from repo api (the white/black list is still available). like 'repo1,repo2,repo3'"
    default: ''
    required: false
  force_update:
    description: "Force to update the destination repo, use '-f' flag to do 'git push'"
    default: 'false'
    required: false
  debug:
    description: "Enable the debug flag to show details log"
    default: 'false'
    required: false
  timeout:
    description: "Set the timeout for every git command, like '600'=>600s, '30m'=>30mins, '1h'=>1hour"
    default: '30m'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dst_key }}
    - ${{ inputs.dst_token }}
    - ${{ inputs.src }}
    - ${{ inputs.dst }}
    - ${{ inputs.account_type }}
    - ${{ inputs.clone_style }}
    - ${{ inputs.cache_path }}
    - ${{ inputs.black_list }}
    - ${{ inputs.white_list }}
    - ${{ inputs.static_list }}
    - ${{ inputs.force_update }}
    - ${{ inputs.debug }}
    - ${{ inputs.timeout }}